oauth_apps: 
  facebook:
    app_key: ""
    app_secret: ""

  google:
    app_key: ""
    app_secret: ""

  linkedin:
    app_key: ""
    app_secret: ""

vimeo_app:
  consumer_key: ""
  consumer_secret: ""
  token: ""
  secret: ""

email_settings:
  contact_us_recipients: "admin@lazuli.com"
  default_from_email: "no-reply@lazuli.com"