oauth_apps: 
  facebook:
    app_key: ""
    app_secret: ""

  google:
    app_key: ""
    app_secret: ""

  linkedin:
    app_key: ""
    app_secret: ""

vimeo_app:
  consumer_key: ""
  consumer_secret: ""
  token: ""
  secret: ""